bin_path: ./binaries/
birth_rate_high: 1.0
birth_rate_low: 1.0
death_rate_high: 0.6
death_rate_low: 0.6
distribution: Poisson
extant_species_high: 301
extant_species_low: 300
frequency_threshold: 0.2
n_genes: 1000
n_sp_trees: 150
output_folder: /media/enzo/Stockage/Output_extinction/output_s3_2/
parameters_estimation_gene_proportion: 0.1
parent_path: ..
sampled_species_high: 61
sampled_species_low: 60
seed: 301
start_index: 0
transfer_rate_high: 0.025
transfer_rate_low: 0.025

normalize_trees: true