bin_path: ./binaries/
birth_rate_high: 1.0
birth_rate_low: 1.0
death_rate_high: 0.3
death_rate_low: 0.3
distribution: Poisson
extant_species_high: 201
extant_species_low: 200
frequency_threshold: 0.2
n_genes: 1000
n_sp_trees: 50
output_folder: ../Output/output_s5_1/
parameters_estimation_gene_proportion: 0.1
parent_path: ..
sampled_species_high: 61
sampled_species_low: 60
seed: 118
start_index: 0
transfer_rate_high: 0.025
transfer_rate_low: 0.025

normalize_trees: false